version: "2"

services:
    quotedb:
        build: .
        volumes:
            - ./data:/opt/quotedb/data
        ports:
            - 3000:8080
        working_dir: /opt/quotedb
        command: /bin/quotedb /opt/quotedb/data/config.yaml
