version: "2"

services:
    quotedb:
        build: .
        volumes:
            - ./data:/go/src/github.com/n7st/quoteDB/data
        working_dir: /go/src/github.com/n7st/quoteDB
        ports:
            - 3000:8080
        command: go run cmd/quoteDB/main.go /go/src/github.com/n7st/quoteDB/data/config.yaml
